spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/venkatesh-joshi-digivalet/config-server-test
          default-label: master
          search-paths:
          - '*service'
server:
  port: 8888
